<a href="https://colab.research.google.com/github/MS-2039852/MAT-421/blob/main/Lesson_D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1.1 Introduction**


We will start by defining some key concepts and operations in linear algebra and giving examples of how they can be realized in Python.

*   **Vector -** A vector in ℝ𝑛 is an 𝑛-tuple, or point, in ℝ𝑛

* **Row Vector -** A vector written horizontally (i.e., with the elements of the vector next to each other) 
*   **Column Vector -** A vector wriitten vertically (i.e., with the elements of the vector on top of each other.

Ex. Create a row vector and column vector, and show the shape of the vectors.


In [3]:
import numpy as np
vector_row = np.array([[1, -5, 3, 2, 4]])
vector_column = np.array([[1], 
                          [2], 
                          [3], 
                          [4]])
print(vector_row.shape)
print(vector_column.shape)

(1, 5)
(4, 1)


Ex. Transpose the row vector we defined above into a column vector and calculate the 𝐿1
, 𝐿2
, and 𝐿∞
 norm of it. Verify that the 𝐿∞
 norm of a vector is equivalent to the maximum value of the elements in the vector.

In [5]:
from numpy.linalg import norm
new_vector = vector_row.T
print(new_vector)
norm_1 = norm(new_vector, 1)
norm_2 = norm(new_vector, 2)
norm_inf = norm(new_vector, np.inf)
print('L_1 is: %.1f'%norm_1)
print('L_2 is: %.1f'%norm_2)
print('L_inf is: %.1f'%norm_inf)

[[ 1]
 [-5]
 [ 3]
 [ 2]
 [ 4]]
L_1 is: 15.0
L_2 is: 7.4
L_inf is: 5.0


*   **Vector Addition -** the pairwise addition of each of the elements of the added vectors. 
*   **Scalar Multiplication -** the product of a vector and a scalar (i.e., a number in ℝ ... the product of each element of the vector by the scalar.
*   **Dot Product -** The dot product of two vectors is the sum of the product of the respective elements in each vector and is denoted by ⋅
, and 𝑣⋅𝑤
*   **The Angle Between Two Vectors (𝜃) -** is defined by the formula:

𝑣⋅𝑤=‖𝑣‖2‖𝑤‖2cos𝜃

Ex. Compute the angle between the vectors 𝑣=[10,9,3] and 𝑤=[2,5,12].

In [6]:
from numpy import arccos, dot

v = np.array([[10, 9, 3]])
w = np.array([[2, 5, 12]])
theta = \
    arccos(dot(v, w.T)/(norm(v)*norm(w)))
print(theta)

[[0.97992471]]


*   **Perpendicular/Orthoogonal -** If the angle between the vectors, 𝜃=𝜋/2
, then the vectors are said to be perpendicular or orthogonal, and the dot product is 0.

In [7]:
from numpy import arccos, dot

v = np.array([[10, 9, 3]])
w = np.array([[2, 5, 12]])
theta = \
    arccos(dot(v, w.T)/(norm(v)*norm(w)))
print(theta)

[[0.97992471]]



*   **Cross Product -** the cross product between two vectors, 𝑣
 and 𝑤 is written 𝑣×𝑤. It is defined by 𝑣×𝑤=‖𝑣‖2‖𝑤‖2sin(𝜃)n, where 𝜃is the angle between the 𝑣and 𝑤(which can be computed from the dot product) and 𝑛 is a vector perpendicular to both 𝑣 and 𝑤 with unit length (i.e., the length is one).

 Ex. Given the vectors 𝑣=[0,2,0] nd 𝑤=[3,0,0], use the Numpy function cross to compute the cross product of v and w.



In [ ]:
v = np.array([[0, 2, 0]])
w = np.array([[3, 0, 0]])
print(np.cross(v, w))

**1.2 Elements of Linear Algebra**






*   **Linear combination** -a new vector constructed from a
subset by multiplying each vector by a constant and adding the results. A
linear subspace is a result of linear combination.

Ex. -Given the row vectors 𝑣=[0,3,2]𝑤=[4,1,1]and 𝑢=[0,−2,0]write the vector 𝑥=[−8,−1,4]as a linear combination of 𝑣, 𝑤, and 𝑢.





In [8]:
v = np.array([[0, 3, 2]])
w = np.array([[4, 1, 1]])
u = np.array([[0, -2, 0]])
x = 3*v-2*w+4*u
print(x)

[[-8 -1  4]]




*   **Linear Subspace** -a linear subspace of V is a subset U ⊆ V
that is closed under vector addition and scalar multiplication. That is, for all
u1,u2 ∈ U and α∈ R, it holds that
u1 +u2 ∈ U,and αu1 ∈ U.
*   **Span-** Let w1,...,wm ∈ V . The span of {w1,...,wm}, denoted
span(w1,...,wm), is the set of all linear combinations of the wj ’s. That is,
span(w1,...,wm)=
{ m
∑j=1
αj wj : α1,...,αm ∈ R
}
*  **Column Space-** Let A ∈ Rn×m be an n×m matrix with columns
a1,...,am ∈ Rn. The column space of A, denoted col(A), is the span of the
columns of A, that is, col(A)=span(a1,...,am)∈ Rn.



*  **Linear Independence** - a list of column vectors u1,...,um is linearly independent if none of them can be written as a linear combinations of the others.
*   **Dimension Theorem** - Let U be a linear subspace of V. Any basis of U has the same number of elements. All bases of U have the same length and same number of elements is dim(U).



*   **Orthonormality-** Aa list of vectors {u1,...,um} is orthonormal if the u's are pairwise orthogonal and each has a norm 1 .
*   **Orthogonal Projection -** Let U ⊆ V be a linear subspace with orthonormal basis q1,...,qm. The orthogonal porjection of v ∊ V on U is Pu v = sum(j=1)< v , qj > qj.


*   **Best Approximation Theorem -** Let U ⊆ V be a linear subspace with orthonormal basis q1,...,qm let v ∊ V. For any u ∊ U. ||v-Pu v|| <= ||v-u||.
*   **Cauchy-Schwarz -** For any u1 v ∊ V , |<u,v>| <= ||u|| ||v||


*   **Gram-Schmidt -** Let a1,...,am in R^n be linearly independent. Then there exists an orthonormal basis, q1,...,qm of span(a1,...,am).
*   **Eigenvalues and Eigenvectors -** Let A ∊ R^(dxd) be a square matrix. Then 𝜆 ∊ R is an eigenvalue of A if there exists a non-zero vector x != 0 such that Ax = 𝜆x. Vector x is an eigenvector.








In [9]:
import numpy as np
from numpy.linalg import eig
x = np.array([ [2, 3], [6, 2] ])
w,v = eig(x)
print('E-value:', w)
print('E-vector', v)

E-value: [ 6.24264069 -2.24264069]
E-vector [[ 0.57735027 -0.57735027]
 [ 0.81649658  0.81649658]]


**1.3 Linear Regression**

**QR Method -**  a preferred method for finding all eigenvalues for a matrix using the Gram-Schmidt technique.

Ex.- Use the qr function in numpy.linalg to decompose matrix 
𝐴=[1,3] 
  [4, 2]
And verify the results.


In [10]:
import numpy as np
from numpy.linalg import qr
a = np.array([[1, 3], 
              [4, 2]])

q, r = qr(a)

print('Q:', q)
print('R:', r)

b = np.dot(q, r)
print('QR:', b)

Q: [[-0.24253563 -0.9701425 ]
 [-0.9701425   0.24253563]]
R: [[-4.12310563 -2.66789188]
 [ 0.         -2.42535625]]
QR: [[1. 3.]
 [4. 2.]]


Ex. Use the QR method to get the eigenvalues of matrix 
𝐴=[1,5]
  [6,3]
  Do 20 iterations, and print out the 1st, 5th, 10th, and 20th iteration.


In [11]:
a = np.array([[1, 5], 
              [6, 3]])
p = [1, 5, 10, 20]
for i in range(20):
    q, r = qr(a)
    a = np.dot(r, q)
    if i+1 in p:
        print(f'Iteration {i+1}:')
        print(a)

Iteration 1:
[[ 4.72972973  5.37837838]
 [ 4.37837838 -0.72972973]]
Iteration 5:
[[ 7.53219819  1.30298389]
 [ 0.30298389 -3.53219819]]
Iteration 10:
[[ 7.56839712e+00 -9.92903126e-01]
 [ 7.09687381e-03 -3.56839712e+00]]
Iteration 20:
[[ 7.56776471e+00 -9.99996151e-01]
 [ 3.84860377e-06 -3.56776471e+00]]
